apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-v2
  labels:
    app: catalog
    service: catalog
    version: v2
spec:
  selector:
    matchLabels:
      app: catalog
      service: catalog
      version: v2
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        service: catalog
        version: v2
    spec:
      volumes:
      - name: catalog-data
        emptyDir: {}
      containers:
      - image: rroque99/catalog:awswest
        name: catalog
        imagePullPolicy: Always
        env:
        - name: CATALOG_DB_HOST
          value: 'catalog-mongo'
        - name: CATALOG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-mongo-pass
              key: password
        - name: CATALOG_DB_PORT
          value: '27017'
        - name: CATALOG_DB_USERNAME
          value: 'mongoadmin'
        - name: CATALOG_PORT
          value: '8082'
        ports:
        - containerPort: 8082
          name: http-catalog
        volumeMounts:
        - mountPath: "/data"
          name: "catalog-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        args: ["--reporter.grpc.host-port=wavefront-jaeger-proxy.wavefront-jaeger.svc.cluster.local:14250"]